/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_cesarbrito;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        tf_descripcion = new javax.swing.JTextField();
        tf_autor = new javax.swing.JTextField();
        rb_fantasia = new javax.swing.JRadioButton();
        rb_romance = new javax.swing.JRadioButton();
        rb_accion = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        tf_puntaje = new javax.swing.JTextField();
        tf_copias = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        tf_edicion = new javax.swing.JTextField();
        dc_year = new com.toedter.calendar.JYearChooser();
        agregar_libro = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_titulo_m = new javax.swing.JTextField();
        tf_descripcion_m = new javax.swing.JTextField();
        tf_autor_m = new javax.swing.JTextField();
        rb_fantasia_m = new javax.swing.JRadioButton();
        rb_romance_m = new javax.swing.JRadioButton();
        rb_accion_m = new javax.swing.JRadioButton();
        rb_historia_m = new javax.swing.JRadioButton();
        tf_puntaje_m = new javax.swing.JTextField();
        tf_copias_m = new javax.swing.JTextField();
        tf_valor_m = new javax.swing.JTextField();
        tf_edicion_m = new javax.swing.JTextField();
        dc_year_m = new com.toedter.calendar.JYearChooser();
        cb_libros = new javax.swing.JComboBox<>();
        modificar_libro = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_libros = new javax.swing.JTable();
        eliminar_libros = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_telefono = new javax.swing.JTextField();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        dc_nacimiento = new com.toedter.calendar.JDateChooser();
        agregar_usuario = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_user_m = new javax.swing.JTextField();
        tf_pass_m = new javax.swing.JTextField();
        tf_correo_m = new javax.swing.JTextField();
        tf_nombre_m = new javax.swing.JTextField();
        rb_m_m = new javax.swing.JRadioButton();
        rb_f_m = new javax.swing.JRadioButton();
        tf_telefono_m = new javax.swing.JTextField();
        dc_nacimiento_m = new com.toedter.calendar.JDateChooser();
        cb_usuarios = new javax.swing.JComboBox<>();
        modificar_usuario = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        tf_userLogin = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tf_passLogin = new javax.swing.JTextField();
        SignIN = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        usuarios_pane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        devolver_libros = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        devolverLibro = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sacarLibros = new javax.swing.JTable();
        sacar_libro_button = new javax.swing.JButton();
        infodelibro = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo:");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Genero:");

        jLabel5.setText("Puntaje(1-5);");

        jLabel6.setText("Copias:");

        jLabel7.setText("Valor:");

        jLabel8.setText("Edicion:");

        jLabel9.setText("Año de Publicacion:");

        buttonGroup1.add(rb_fantasia);
        rb_fantasia.setText("Fantasia");

        buttonGroup1.add(rb_romance);
        rb_romance.setText("Romance");

        buttonGroup1.add(rb_accion);
        rb_accion.setText("Accion");

        buttonGroup1.add(rb_historia);
        rb_historia.setText("Historia");

        agregar_libro.setText("Agregar");
        agregar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_libroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_titulo)
                        .addComponent(tf_descripcion)
                        .addComponent(tf_autor, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_edicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(tf_valor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_copias, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_puntaje, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rb_fantasia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_romance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_accion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_historia))
                    .addComponent(dc_year, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_fantasia)
                    .addComponent(rb_romance)
                    .addComponent(rb_accion)
                    .addComponent(rb_historia))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(dc_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(agregar_libro)
                .addGap(53, 53, 53))
        );

        jTabbedPane3.addTab("Agregar", jPanel7);

        jLabel10.setText("Titulo:");

        jLabel11.setText("Descripcion:");

        jLabel12.setText("Autor:");

        jLabel13.setText("Genero:");

        jLabel14.setText("Puntaje(1-5);");

        jLabel15.setText("Copias:");

        jLabel16.setText("Valor:");

        jLabel17.setText("Edicion:");

        jLabel18.setText("Año de Publicacion:");

        buttonGroup2.add(rb_fantasia_m);
        rb_fantasia_m.setText("Fantasia");

        buttonGroup2.add(rb_romance_m);
        rb_romance_m.setText("Romance");

        buttonGroup2.add(rb_accion_m);
        rb_accion_m.setText("Accion");

        buttonGroup2.add(rb_historia_m);
        rb_historia_m.setText("Historia");

        cb_libros.setMaximumRowCount(100);
        cb_libros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_librosItemStateChanged(evt);
            }
        });

        modificar_libro.setText("Modificar");
        modificar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_libroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_titulo_m)
                                        .addComponent(tf_descripcion_m)
                                        .addComponent(tf_autor_m, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_edicion_m, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_valor_m, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_copias_m, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_puntaje_m, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(rb_fantasia_m)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_romance_m)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_accion_m)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_historia_m))
                                    .addComponent(dc_year_m, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(modificar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_titulo_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_descripcion_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_autor_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rb_fantasia_m)
                    .addComponent(rb_romance_m)
                    .addComponent(rb_accion_m)
                    .addComponent(rb_historia_m))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_puntaje_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_copias_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_valor_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_edicion_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(dc_year_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modificar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar", jPanel8);

        tabla_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Genero", "Año de Publicacion"
            }
        ));
        jScrollPane3.setViewportView(tabla_libros);

        eliminar_libros.setText("Eliminar");
        eliminar_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_librosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(eliminar_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar_libros, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("Eliminar", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        jTabbedPane2.addTab("Libros", jPanel3);

        jLabel19.setText("Usuario:");

        jLabel20.setText("Contraseña:");

        jLabel21.setText("Correo:");

        jLabel22.setText("Nombre:");

        jLabel23.setText("Masculino:");

        jLabel24.setText("Telefono:");

        jLabel25.setText("Nacimiento:");

        buttonGroup3.add(rb_m);
        rb_m.setText("Masculino");

        buttonGroup3.add(rb_f);
        rb_f.setText("Femenino");

        agregar_usuario.setText("Agregar");
        agregar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_user)
                            .addComponent(tf_pass)
                            .addComponent(tf_correo)
                            .addComponent(tf_nombre)
                            .addComponent(tf_telefono)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rb_m)
                                .addGap(41, 41, 41)
                                .addComponent(rb_f))
                            .addComponent(dc_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(agregar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rb_m)
                    .addComponent(rb_f))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(dc_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(agregar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Agregar", jPanel10);

        jLabel26.setText("Usuario:");

        jLabel27.setText("Contraseña:");

        jLabel28.setText("Correo:");

        jLabel29.setText("Nombre:");

        jLabel30.setText("Masculino:");

        jLabel31.setText("Telefono:");

        jLabel32.setText("Nacimiento:");

        buttonGroup4.add(rb_m_m);
        rb_m_m.setText("Masculino");

        buttonGroup4.add(rb_f_m);
        rb_f_m.setText("Femenino");

        cb_usuarios.setMaximumRowCount(100);
        cb_usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuariosItemStateChanged(evt);
            }
        });

        modificar_usuario.setText("Modificar");
        modificar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_user_m)
                            .addComponent(tf_pass_m)
                            .addComponent(tf_correo_m)
                            .addComponent(tf_nombre_m)
                            .addComponent(tf_telefono_m)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(rb_m_m)
                                .addGap(41, 41, 41)
                                .addComponent(rb_f_m))
                            .addComponent(dc_nacimiento_m, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(modificar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_user_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_pass_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_correo_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_nombre_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rb_m_m)
                    .addComponent(rb_f_m))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_telefono_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(dc_nacimiento_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(modificar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Modificar", jPanel11);

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Correo", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(tabla_usuarios);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane4.addTab("Listar", jPanel12);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Usuarios", jPanel4);

        jLabel33.setText("Usuario:");

        jLabel34.setText("Contraseña:");

        SignIN.setText("Sign In");
        SignIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignINActionPerformed(evt);
            }
        });

        jButton3.setText("Sign out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        usuarios_pane.setEnabled(false);

        devolver_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor"
            }
        ));
        jScrollPane5.setViewportView(devolver_libros);

        jLabel35.setText("Mis libros:");

        devolverLibro.setText("Devolver Libro");
        devolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(devolverLibro)
                    .addComponent(jLabel35)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(devolverLibro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuarios_pane.addTab("Devolver Libro", jPanel2);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios_pane.addTab("Prestar a Un Amigo", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios_pane.addTab("Amigos", jPanel15);

        sacarLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor"
            }
        ));
        jScrollPane4.setViewportView(sacarLibros);

        sacar_libro_button.setText("Sacar Libro");
        sacar_libro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacar_libro_buttonActionPerformed(evt);
            }
        });

        infodelibro.setText("Informacion");
        infodelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infodelibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(sacar_libro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(infodelibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacar_libro_button)
                    .addComponent(infodelibro))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        usuarios_pane.addTab("Libros", jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel33)
                    .addComponent(tf_userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(tf_passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(usuarios_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(tf_userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(tf_passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(SignIN)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(usuarios_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Login", jPanel5);

        historial.setEditable(false);
        historial.setColumns(20);
        historial.setRows(5);
        historial.setText("El admin ha ingresado al usuario");
        jScrollPane1.setViewportView(historial);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Historial", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_libroActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = tf_titulo.getText();
            String descripcion = tf_descripcion.getText();
            String autor = tf_autor.getText();
            String genero = "";
            if (rb_accion.isSelected()) {
                genero = "Accion";
            } else if (rb_fantasia.isSelected()) {
                genero = "Fantasia";
            } else if (rb_historia.isSelected()) {
                genero = "Historia";
            } else if (rb_romance.isSelected()) {
                genero = "Romance";
            }
            int puntaje = Integer.parseInt(tf_puntaje.getText());
            int copias = Integer.parseInt(tf_copias.getText());
            int valor = Integer.parseInt(tf_valor.getText());
            int edicion = Integer.parseInt(tf_edicion.getText());
            int year = dc_year.getYear();
            tf_titulo.setText("");
            tf_descripcion.setText("");
            tf_autor.setText("");
            tf_puntaje.setText("");
            tf_copias.setText("");
            tf_valor.setText("");
            tf_edicion.setText("");
            dc_year.setYear(2021);
            libros.add(new Libro(titulo, descripcion, genero, autor, puntaje, copias, valor, edicion, year));
            Object[] libro = {titulo, autor, genero, year};
            DefaultTableModel modelo = (DefaultTableModel) tabla_libros.getModel();
            modelo.addRow(libro);
            tabla_libros.setModel(modelo);
            /////////
            Libro x = new Libro(titulo, descripcion, genero, autor, puntaje, copias, valor, edicion, year);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_libros.getModel();
            dc.addElement(x);
            cb_libros.setModel(dc);
            historial.append("\nFue creado el libro: " + x);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_agregar_libroActionPerformed

    private void eliminar_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_librosActionPerformed
        // TODO add your handling code here:
        try {
            if (tabla_libros.getSelectedRow() >= 0) {
                int po = tabla_libros.getSelectedRow();
                Libro x = libros.get(tabla_libros.getSelectedRow());
                libros.remove(tabla_libros.getSelectedRow());
                DefaultTableModel modelo = (DefaultTableModel) tabla_libros.getModel();
                modelo.removeRow(tabla_libros.getSelectedRow());
                tabla_libros.setModel(modelo);
                DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_libros.getModel();
                dc.removeElementAt(po);
                cb_libros.setModel(dc);
                if (dc.getSize() == 0) {
                    tf_titulo_m.setText("");
                    tf_descripcion_m.setText("");
                    tf_autor_m.setText("");
                    tf_puntaje_m.setText("");
                    tf_copias_m.setText("");
                    tf_valor_m.setText("");
                    tf_edicion_m.setText("");
                    dc_year_m.setYear(2021);

                    rb_accion_m.setSelected(false);

                    rb_fantasia_m.setSelected(false);

                    rb_historia_m.setSelected(false);

                    rb_romance_m.setSelected(false);

                }
                historial.append("\nFue eliminado el libro: " + x);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_eliminar_librosActionPerformed

    private void cb_librosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_librosItemStateChanged
        // TODO add your handling code here:
        try {
            Libro p = (Libro) cb_libros.getSelectedItem();
            tf_titulo_m.setText(p.getTitulo());
            tf_descripcion_m.setText(p.getDescripcion());
            tf_autor_m.setText(p.getAutor());
            tf_puntaje_m.setText(String.valueOf(p.getPuntaje()));
            tf_copias_m.setText(String.valueOf(p.getCopias()));
            tf_valor_m.setText(String.valueOf(p.getValor()));
            tf_edicion_m.setText(String.valueOf(p.getEdicion()));
            dc_year_m.setYear(p.getPublicacion());
            if (p.getGenero().equals("Accion")) {
                rb_accion_m.setSelected(true);
            } else if (p.getGenero().equals("Fantasia")) {
                rb_fantasia_m.setSelected(true);
            } else if (p.getGenero().equals("Historia")) {
                rb_historia_m.setSelected(true);
            } else if (p.getGenero().equals("Romance")) {
                rb_romance_m.setSelected(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_cb_librosItemStateChanged

    private void modificar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_libroActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = tf_titulo_m.getText();
            String descripcion = tf_descripcion_m.getText();
            String autor = tf_autor_m.getText();
            String genero = "";
            if (rb_accion_m.isSelected()) {
                genero = "Accion";
            } else if (rb_fantasia_m.isSelected()) {
                genero = "Fantasia";
            } else if (rb_historia_m.isSelected()) {
                genero = "Historia";
            } else if (rb_romance_m.isSelected()) {
                genero = "Romance";
            }
            int puntaje = Integer.parseInt(tf_puntaje_m.getText());
            int copias = Integer.parseInt(tf_copias_m.getText());
            int valor = Integer.parseInt(tf_valor_m.getText());
            int edicion = Integer.parseInt(tf_edicion_m.getText());
            int year = dc_year_m.getYear();
            int po = cb_libros.getSelectedIndex();
            libros.get(po).setAutor(autor);
            libros.get(po).setCopias(copias);
            libros.get(po).setDescripcion(descripcion);
            libros.get(po).setEdicion(edicion);
            libros.get(po).setGenero(genero);
            libros.get(po).setPublicacion(year);
            libros.get(po).setPuntaje(puntaje);
            libros.get(po).setTitulo(titulo);
            libros.get(po).setValor(valor);

            Object[] libro = {titulo, autor, genero, year};
            Libro x = new Libro(titulo, descripcion, genero, autor, puntaje, copias, valor, edicion, year);
            DefaultTableModel modelo = (DefaultTableModel) tabla_libros.getModel();
            modelo.insertRow(cb_libros.getSelectedIndex(), libro);
            modelo.removeRow(cb_libros.getSelectedIndex() + 1);
            tabla_libros.setModel(modelo);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_libros.getModel();
            dc.setSelectedItem(x);
            dc.insertElementAt(x, po);
            dc.removeElementAt(po + 1);
            cb_libros.setModel(dc);
            historial.append("\nFue modificado el libro: " + x);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_modificar_libroActionPerformed

    private void agregar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_usuarioActionPerformed
        // TODO add your handling code here:
        try {
            String username = tf_user.getText();
            String password = tf_pass.getText();
            String correo = tf_correo.getText();
            String nombre = tf_nombre.getText();
            String genero = "";
            if (rb_m.isSelected()) {
                genero = "Masculino";
            } else if (rb_f.isSelected()) {
                genero = "Femenino";
            }
            int telefono = Integer.parseInt(tf_telefono.getText());
            Date nacimiento = dc_nacimiento.getDate();
            Usuario x = new Usuario(username, password, correo, nombre, genero, telefono, nacimiento);
            usuarios.add(x);
            tf_user.setText("");
            tf_pass.setText("");
            tf_correo.setText("");
            tf_nombre.setText("");
            tf_telefono.setText("");
            dc_nacimiento.setDate(new Date());
            Object[] nuevo = {username, nombre, correo, telefono};
            DefaultTableModel modelo = (DefaultTableModel) tabla_usuarios.getModel();
            modelo.addRow(nuevo);
            tabla_usuarios.setModel(modelo);
            /////////
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_usuarios.getModel();
            dc.addElement(x);
            cb_usuarios.setModel(dc);
            historial.append("\nFue creado el usuario: " + x);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }

    }//GEN-LAST:event_agregar_usuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (tabla_usuarios.getSelectedRow() >= 0) {
                int po = tabla_usuarios.getSelectedRow();
                Usuario x = usuarios.get(tabla_usuarios.getSelectedRow());
                usuarios.remove(tabla_usuarios.getSelectedRow());
                DefaultTableModel modelo = (DefaultTableModel) tabla_usuarios.getModel();
                modelo.removeRow(tabla_usuarios.getSelectedRow());
                tabla_usuarios.setModel(modelo);
                DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_usuarios.getModel();
                dc.removeElementAt(po);
                cb_usuarios.setModel(dc);
                if (dc.getSize() == 0) {
                    tf_user_m.setText("");
                    tf_pass_m.setText("");
                    tf_correo_m.setText("");
                    tf_nombre_m.setText("");
                    tf_telefono_m.setText("");
                    dc_nacimiento_m.setDate(new Date());
                    rb_m_m.setSelected(false);
                    rb_f_m.setSelected(false);
                }
                historial.append("\nFue eliminado el usuario: " + x);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_usuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuariosItemStateChanged
        // TODO add your handling code here:
        try {
            Usuario p = (Usuario) cb_usuarios.getSelectedItem();
            tf_user_m.setText(p.getUsername());
            tf_pass_m.setText(p.getPassword());
            tf_correo_m.setText(p.getCorreo());
            tf_nombre_m.setText(p.getNombre());
            tf_telefono_m.setText(String.valueOf(p.getTelefono()));
            dc_nacimiento_m.setDate(p.getNacimiento());
            if (p.getGenero().equals("Masculino")) {
                rb_accion_m.setSelected(true);
            } else if (p.getGenero().equals("Femenino")) {
                rb_fantasia_m.setSelected(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_cb_usuariosItemStateChanged

    private void modificar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_usuarioActionPerformed
        // TODO add your handling code here:
        try {
            String username = tf_user_m.getText();
            String password = tf_pass_m.getText();
            String correo = tf_correo_m.getText();
            String nombre = tf_nombre_m.getText();
            String genero = "";
            if (rb_m_m.isSelected()) {
                genero = "Masculino";
            } else if (rb_f_m.isSelected()) {
                genero = "Femenino";
            }
            int telefono = Integer.parseInt(tf_telefono_m.getText());
            Date nacimiento = dc_nacimiento_m.getDate();
            int po = cb_usuarios.getSelectedIndex();
            usuarios.get(po).setCorreo(correo);
            usuarios.get(po).setGenero(genero);
            usuarios.get(po).setNacimiento(nacimiento);
            usuarios.get(po).setNombre(nombre);
            usuarios.get(po).setPassword(password);
            usuarios.get(po).setTelefono(telefono);
            usuarios.get(po).setUsername(username);
            Object[] nuevo = {username, nombre, correo, telefono};
            Usuario x = new Usuario(username, password, correo, nombre, genero, telefono, nacimiento);
            DefaultTableModel modelo = (DefaultTableModel) tabla_usuarios.getModel();
            modelo.insertRow(cb_usuarios.getSelectedIndex(), nuevo);
            modelo.removeRow(cb_usuarios.getSelectedIndex() + 1);
            tabla_usuarios.setModel(modelo);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_usuarios.getModel();
            dc.setSelectedItem(x);
            dc.insertElementAt(x, po);
            dc.removeElementAt(po + 1);
            cb_usuarios.setModel(dc);
            historial.append("\nFue modificado el usuario: " + x);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }

    }//GEN-LAST:event_modificar_usuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        usuarios_pane.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SignINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignINActionPerformed
        // TODO add your handling code here:
        try {
            String user = tf_userLogin.getText();
            String pass = tf_passLogin.getText();
            for (int i = 0; i < usuarios.size(); i++) {
                if (user.equals(usuarios.get(i).getUsername()) && pass.equals(usuarios.get(i).getPassword())) {
                    seleccionado = i;
                    usuarios_pane.setEnabled(true);
                    historial.append("\nHa ingresado el usuario: " + usuarios.get(i));
                }
            }
            DefaultTableModel modelo = (DefaultTableModel) sacarLibros.getModel();
            for (int i = 0; i < libros.size(); i++) {
                Object[] nuevo = {libros.get(i).getTitulo(), libros.get(i).getAutor()};
                modelo.addRow(nuevo);
            }
            sacarLibros.setModel(modelo);
            //////
            //devolver_libros
            DefaultTableModel model = (DefaultTableModel) devolver_libros.getModel();
            for (int i = 0; i < usuarios.get(seleccionado).getLibros().size(); i++) {
                Object[] nuevo = {usuarios.get(seleccionado).getLibros().get(i).getTitulo(), usuarios.get(seleccionado).getLibros().get(i).getAutor()};
                model.addRow(nuevo);
            }
            // devolver_libros
            devolver_libros.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_SignINActionPerformed

    private void sacar_libro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacar_libro_buttonActionPerformed
        // TODO add your handling code here:
        try {
            if (sacarLibros.getSelectedRow() >= 0) {
                int po = sacarLibros.getSelectedRow();
                Libro x = libros.get(sacarLibros.getSelectedRow());
                usuarios.get(seleccionado).getLibros().add(libros.get(po));
                JOptionPane.showMessageDialog(this, "** HA SACADO EL LIBRO **");
                DefaultTableModel model = (DefaultTableModel) devolver_libros.getModel();
                Object[] nuevo = {x.getTitulo(), x.getAutor()};
                model.addRow(nuevo);
                devolver_libros.setModel(model);
                historial.append("\nEl usuario: " + usuarios.get(seleccionado) + " ha sacado el libro el libro: " + x);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_sacar_libro_buttonActionPerformed

    private void infodelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infodelibroActionPerformed
        // TODO add your handling code here:
        try {
            if (sacarLibros.getSelectedRow() >= 0) {
                Libro x = libros.get(sacarLibros.getSelectedRow());
                String acum = "";
                acum += "Titulo: " + x.getTitulo()
                        + "\nDescripcion: " + x.getDescripcion()
                        + "\nGenero: " + x.getGenero()
                        + "\nAutor: " + x.getAutor()
                        + "\nPuntaje: " + x.getPuntaje()
                        + "\nValor: " + x.getValor()
                        + "\nEdicion: " + x.getEdicion()
                        + "\nAño de Publicacion: " + x.getPublicacion();
                JOptionPane.showMessageDialog(this, acum);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_infodelibroActionPerformed

    private void devolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLibroActionPerformed
        // TODO add your handling code here:
        try {
            if (devolver_libros.getSelectedRow() >= 0) {
                int po = devolver_libros.getSelectedRow();
                Libro x = libros.get(sacarLibros.getSelectedRow());
                usuarios.get(seleccionado).getLibros().remove(po);
                JOptionPane.showMessageDialog(this, "** HA DEVUELTO EL LIBRO **");
                DefaultTableModel model = (DefaultTableModel) devolver_libros.getModel();
                model.removeRow(devolver_libros.getSelectedRow());
                devolver_libros.setModel(model);
                historial.append("\nEl usuario: " + usuarios.get(seleccionado) + " ha devuelto el libro el libro: " + x);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_devolverLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIN;
    private javax.swing.JButton agregar_libro;
    private javax.swing.JButton agregar_usuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cb_libros;
    private javax.swing.JComboBox<String> cb_usuarios;
    private com.toedter.calendar.JDateChooser dc_nacimiento;
    private com.toedter.calendar.JDateChooser dc_nacimiento_m;
    private com.toedter.calendar.JYearChooser dc_year;
    private com.toedter.calendar.JYearChooser dc_year_m;
    private javax.swing.JButton devolverLibro;
    private javax.swing.JTable devolver_libros;
    private javax.swing.JButton eliminar_libros;
    private javax.swing.JTextArea historial;
    private javax.swing.JButton infodelibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton modificar_libro;
    private javax.swing.JButton modificar_usuario;
    private javax.swing.JRadioButton rb_accion;
    private javax.swing.JRadioButton rb_accion_m;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_f_m;
    private javax.swing.JRadioButton rb_fantasia;
    private javax.swing.JRadioButton rb_fantasia_m;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_historia_m;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_m_m;
    private javax.swing.JRadioButton rb_romance;
    private javax.swing.JRadioButton rb_romance_m;
    private javax.swing.JTable sacarLibros;
    private javax.swing.JButton sacar_libro_button;
    private javax.swing.JTable tabla_libros;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autor_m;
    private javax.swing.JTextField tf_copias;
    private javax.swing.JTextField tf_copias_m;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo_m;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_descripcion_m;
    private javax.swing.JTextField tf_edicion;
    private javax.swing.JTextField tf_edicion_m;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre_m;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_passLogin;
    private javax.swing.JTextField tf_pass_m;
    private javax.swing.JTextField tf_puntaje;
    private javax.swing.JTextField tf_puntaje_m;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_telefono_m;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_titulo_m;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_userLogin;
    private javax.swing.JTextField tf_user_m;
    private javax.swing.JTextField tf_valor;
    private javax.swing.JTextField tf_valor_m;
    private javax.swing.JTabbedPane usuarios_pane;
    // End of variables declaration//GEN-END:variables
    ArrayList<Libro> libros = new ArrayList();
    ArrayList<Usuario> usuarios = new ArrayList();
    int seleccionado = 0;
}
